name: CheatMenu
version: ${project.version}
main: io.github.copyright135.cheatmenu.CheatMenu
description: Menu with a bunch of cheats
api-version: 1.13

commands:
  cheatmenu:
    aliases: [cm, cheat, cheats]